controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute
app_logout:
  path: /logout
  methods: GET
homepage:
  path: /accueil
  controller: 'App\Controller\HomeController::index'
  methods: GET
basket_add_product:
  path: "/basket/add/{idProduct}"
  controller: 'App\Controller\BasketController::handleEventCartForm'
basket_modify_quantity:
  path: "/basket/modify/quantity"
  controller: 'App\Controller\BasketController::handleEventCountForm'
basket_clear_cart:
  path: "/basket/clear/cart"
  controller: 'App\Controller\BasketController::handleEventClearForm'
