controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute
app_logout:
  path: /logout
  methods: GET
homepage:
  path: /accueil
  controller: 'App\Controller\HomeController::index'
  methods: GET
basket_add_product:
  path: "/basket/add/{idProduct}"
  controller: 'App\Controller\BasketController::handleEventCartForm'
